In [2]:
print('hello world')

hello world


In [3]:
import numpy as np

In [4]:
a1 = np.array([6,7,8,9])
a1

array([6, 7, 8, 9])

In [5]:
type(a1)

numpy.ndarray

In [6]:
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [7]:
np.array(list1)

array([1, 2, 3, 4])

In [8]:
np.array([1.1,2.2,3.3,4.4])

array([1.1, 2.2, 3.3, 4.4])

### 3d array

In [9]:
b2 = [[[1,2,3,4],[11,22,33],[34,45,56],[44,55,66,]]]
b2

[[[1, 2, 3, 4], [11, 22, 33], [34, 45, 56], [44, 55, 66]]]

In [10]:
# create an object array to handle irregular-length inner lists
a3 = np.array(b2, dtype=object)
a3

array([[list([1, 2, 3, 4]), list([11, 22, 33]), list([34, 45, 56]),
        list([44, 55, 66])]], dtype=object)

### Zeros and ones

In [13]:
np.zeros((3,4)) # 3 rows, 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:

np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones((2,3,2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

### identity matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### linspace

In [23]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [27]:
np.linspace(10,20,20, dtype=int)

array([10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18,
       18, 19, 20])

In [28]:
np.linspace(10,20,10,endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [29]:
np.linspace(10,20,10, retstep=True)

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 np.float64(1.1111111111111112))

In [30]:
np.linspace(20,30,5, endpoint=False, retstep=True)

(array([20., 22., 24., 26., 28.]), np.float64(2.0))

### random

In [43]:
np.random.rand(1,100)

array([[0.63736768, 0.55151411, 0.79135407, 0.69924421, 0.72327511,
        0.94756889, 0.13554623, 0.02069248, 0.5322735 , 0.18576912,
        0.43368207, 0.03474007, 0.29615637, 0.59507737, 0.7008797 ,
        0.19727615, 0.65042521, 0.167584  , 0.02676367, 0.82549454,
        0.75414902, 0.39105992, 0.88785034, 0.48681024, 0.02076582,
        0.91089245, 0.34315138, 0.2939772 , 0.60564169, 0.20312579,
        0.23263022, 0.85985892, 0.64130327, 0.91761689, 0.53805213,
        0.73766648, 0.00152373, 0.53894396, 0.75570774, 0.33291693,
        0.11119894, 0.77357686, 0.50905001, 0.32701537, 0.82082779,
        0.58651265, 0.93073801, 0.09150579, 0.55138011, 0.71479018,
        0.18662805, 0.05815789, 0.39686931, 0.23989252, 0.93254616,
        0.34789877, 0.9584392 , 0.43000728, 0.64764634, 0.66600018,
        0.77862084, 0.61411619, 0.0814386 , 0.81302487, 0.18859155,
        0.18622847, 0.01087746, 0.59345152, 0.8441031 , 0.49122307,
        0.11522693, 0.24193779, 0.75528649, 0.45

In [44]:
np.random.rand(3)

array([0.02931604, 0.13297759, 0.68093047])

In [45]:
np.random.randn(2,3,2)

array([[[ 0.55480309, -1.15856892],
        [ 0.85258433, -0.78587975],
        [-0.22847898,  0.51590262]],

       [[ 1.33739484, -0.355825  ],
        [ 1.29305544,  0.44196566],
        [ 0.59402773, -0.03352613]]])

In [47]:
np.random.rand(4,5)

array([[0.91553456, 0.88665136, 0.94835318, 0.04831769, 0.61707532],
       [0.98857711, 0.09087933, 0.94262855, 0.03068783, 0.1091419 ],
       [0.52934348, 0.34168164, 0.57995536, 0.72963905, 0.47312697],
       [0.80312425, 0.16414142, 0.86975961, 0.14964062, 0.98433853]])

In [49]:
np.random.randint(30,40)

39

In [51]:
np.random.randint(29,99,3)

array([34, 31, 95], dtype=int32)

In [52]:
np.random.randint(50,100,(4,5))

array([[88, 96, 80, 56, 71],
       [53, 58, 54, 91, 73],
       [97, 84, 85, 95, 57],
       [55, 65, 58, 55, 73]], dtype=int32)

In [57]:
np.random.randint(3,99,(4,3,3))

array([[[34, 40, 17],
        [67, 13, 17],
        [68, 85, 43]],

       [[90, 71,  6],
        [75, 26, 72],
        [97, 82, 65]],

       [[81, 69,  5],
        [33, 83, 37],
        [49, 46, 42]],

       [[26, 41, 81],
        [46, 71,  8],
        [25, 20, 96]]], dtype=int32)

In [58]:
np.random.rand(3,3,3)

array([[[0.92955198, 0.97377627, 0.43856915],
        [0.8149193 , 0.12179714, 0.14867961],
        [0.57089303, 0.96673617, 0.9672156 ]],

       [[0.43482335, 0.42701842, 0.71331824],
        [0.60070633, 0.98928605, 0.46167523],
        [0.47624084, 0.26841041, 0.56768909]],

       [[0.28020293, 0.92927837, 0.90677028],
        [0.30701057, 0.10494   , 0.24092662],
        [0.42015373, 0.92228145, 0.9615765 ]]])

In [60]:
np.arange(20,50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
np.linspace(20,50)

array([20.        , 20.6122449 , 21.2244898 , 21.83673469, 22.44897959,
       23.06122449, 23.67346939, 24.28571429, 24.89795918, 25.51020408,
       26.12244898, 26.73469388, 27.34693878, 27.95918367, 28.57142857,
       29.18367347, 29.79591837, 30.40816327, 31.02040816, 31.63265306,
       32.24489796, 32.85714286, 33.46938776, 34.08163265, 34.69387755,
       35.30612245, 35.91836735, 36.53061224, 37.14285714, 37.75510204,
       38.36734694, 38.97959184, 39.59183673, 40.20408163, 40.81632653,
       41.42857143, 42.04081633, 42.65306122, 43.26530612, 43.87755102,
       44.48979592, 45.10204082, 45.71428571, 46.32653061, 46.93877551,
       47.55102041, 48.16326531, 48.7755102 , 49.3877551 , 50.        ])

In [63]:
np.random.randint(20,50)

27

### numpy methods

In [66]:
arr1 = np.random.randint(40,99,10)
arr1

array([88, 87, 48, 72, 82, 62, 87, 47, 54, 44], dtype=int32)

In [70]:
print(f'the max value of array is {arr1.max()}')
print(f'the min value of array is {arr1.min()}')


the max value of array is 88
the min value of array is 44


In [71]:
arr1.argmax()

np.int64(0)

In [72]:
arr1.argmin()

np.int64(9)

### indexing and slicing

In [73]:
import numpy as np

In [76]:
arr1 = np.arange(20,50,2)
arr1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [80]:
arrindexing = arr1[2:12]
arrindexing

array([24, 26, 28, 30, 32, 34, 36, 38, 40, 42])

In [81]:
negativeindexing = arr1[-13:-3]
negativeindexing

array([24, 26, 28, 30, 32, 34, 36, 38, 40, 42])

In [84]:
arr1[-13:-4:2]

array([24, 28, 32, 36, 40])

In [85]:
arr1[-5:-14:-2]

array([40, 36, 32, 28, 24])

In [87]:
arr1[10:]

array([40, 42, 44, 46, 48])

In [88]:
arr1[:]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [89]:
arr1[::-1]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20])

In [92]:
np.arange(20,100,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [94]:
arr2 = np.arange(20,104,2).reshape(7,6)

In [95]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [96]:
arr2[2,1]

np.int64(46)

In [103]:
arr2[5,2]

np.int64(84)

In [104]:
arr2[[5,2]]

array([[80, 82, 84, 86, 88, 90],
       [44, 46, 48, 50, 52, 54]])

In [107]:
arr2[1:5]

array([[32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [108]:
arr2[1:5, 1:5]

array([[34, 36, 38, 40],
       [46, 48, 50, 52],
       [58, 60, 62, 64],
       [70, 72, 74, 76]])

In [123]:
arr2[1:5:3]

array([[32, 34, 36, 38, 40, 42],
       [68, 70, 72, 74, 76, 78]])

In [126]:
arr2[2]

array([44, 46, 48, 50, 52, 54])

In [127]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr